### ISSUE TITLE
Text reoccurence when text reaches a certain limit

### ISSUE THREAD

**Issue by akasha992** [KoBeWi/Godot-Simple-TODO#2]
### Godot version

v3.5.1 stable

### OS

Windows 10, x64

### Steps to reproduce

1. Make any column and fill with text

![ezgif-3-743c9871ed](https://user-images.githubusercontent.com/115383131/194743274-d109d1c5-9161-491e-be97-d931b0616092.gif)

**Comment by KoBeWi** [comment]
This comes from the fact that I used a hack to update minimum size of the input box. It's fixed in the 4.0 version, because there is a feature that allows that without hacks. Unfortunately I can't really do anything about it in 3.5, so you just have to use short texts.
