### ISSUE TITLE
Wrong column names and an error in Godot 4.0 beta 14

### ISSUE THREAD

**Issue by Mooncat25** [KoBeWi/Godot-Simple-TODO#3]
There is an error when the plugin is used in Godot 4.0 beta 14.

**Steps to reproduce:**
1. At first, you will notice that all column names will be changed to "Column Name", which is the default values.
2. When you try to create a column, an error will be displayed as follow
`res://addons/SimpleTODO/SimpleTODO.gd:76 - Invalid get index 'name_edit' (on base: 'HBoxContainer ()').`

**Fix:**
1. It is easy to fix. Just move `@tool` in `ColumnHeader.gd` to the top of the file so it becomes the first line. That's it.
2. Disable and re-enable the plugin to let it reload. All the custom column names are back.
(I originally wanted to make a pull request but I've messed up with my password so I can't push things for awhile)

Thanks for your plugin. It is simple. But it is useful. :)

**Comment by KoBeWi** [comment]
Thanks for the report, fixed in 853147b932f85bfe71d6c9d56c69fcb5bf7bfd6a
