### ISSUE TITLE
Plugin continues to print errors when in use

### ISSUE THREAD

**Issue by inhalt120g** [KoBeWi/Godot-Simple-TODO#4]
I already asked about this on Twitter but didn't get a reply so here I am :)

v4.2.1.stable.official [b09f793f5]
Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

When using the plugin, it continues printing errors in the console. I can't figure out what exactly triggers it, it looks like every action I do (rearrange the columns, add a new entry) has a 25 % chances of triggering a new error line. So if I use it for a while the console log looks like this:
![image](https://github.com/KoBeWi/Godot-Simple-TODO/assets/106015575/7526ca27-792c-409f-ab2d-ed79f27f3610)

**Comment by KoBeWi** [comment]
The errors print when drag and dropping items. They are harmless, I have to look into it eventually.

**Comment by KoBeWi** [comment]
Fixed by c4a25cc2db1522ba2eb53cabfe2261b1415f803c
