### ISSUE TITLE
[Feature Request] Button to add item to top of column

### ISSUE THREAD

**Issue by JUSTCAMH** [KoBeWi/Godot-Simple-TODO#7]
This is a really handy plugin, thanks! I've got a lot of todo items and like to sort them with high priority stuff at the top and lower stuff at the bottom. But when I want to add a new high priority task, I need to scroll to the bottom of the column, add it, then drag it up.

Add a button at the top of each column (which could go next to the down arrow that collapses the column) which adds a new entry to the top of the column. This will help with adding important tasks that need to be done now!

**Comment by KoBeWi** [comment]
It would be easier to add "Move to Top" button to item's menu. Would that be ok as an alternative?

**Comment by JUSTCAMH** [comment]
Moving the item up is half the problem, but the other half is that the button to add an entry moves further and further down with each new item added to the todo! A button that rests at the top of the column would mean you never need to scroll to add elements. Though move to top is still handy!

**Comment by KoBeWi** [comment]
Implemented in 240959d7a9cdaabc141fe6387f40f388ad9cd8d2

I went with a menu, because there isn't really space for a new button:

![](https://github.com/KoBeWi/Godot-Simple-TODO/raw/master/Media/ReadmeAddTop.gif)

**Comment by JUSTCAMH** [comment]
Thank you so much, looks great!
